version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn run start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
